import type { Metadata } from "next";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar, {
  ISidebarLinks,
} from "@/components/layout/sidebar/app-sidebar";
import { Home, User } from "lucide-react";
import AppHeader from "@/components/layout/header/app-header";
import AppMain from "@/components/layout/main/app-main";
import { BreadcrumStoreProvider } from "@/providers/breadcrum-store-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarLinks: ISidebarLinks = {
    groups: [
      { elements: [{ label: "Home", link: "/", icon: Home }] },
      {
        label: "Settings",
        elements: [{ label: "User", link: "/users", icon: User }],
      },
    ],
  };

  return (
    <html lang="en">
      <body>
        <BreadcrumStoreProvider>
          <SidebarProvider>
            <AppSidebar links={sidebarLinks} />
            <SidebarInset>
              <AppHeader withSidebarTrigger />
              <main>
                <AppMain>{children}</AppMain>
              </main>
            </SidebarInset>
          </SidebarProvider>
        </BreadcrumStoreProvider>
      </body>
    </html>
  );
}
