import type { Metadata } from "next";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar, {
  ISidebarLinks,
} from "@/components/layout/sidebar/app-sidebar";
import { Home, User } from "lucide-react";
import AppHeader from "@/components/layout/header/app-header";
import AppMain from "@/components/layout/main/app-main";
import { BreadcrumStoreProvider } from "@/providers/breadcrum-store-provider";
import { UserStoreProvider } from "@/providers/user-store-provider";
import { auth } from "@/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarLinks: ISidebarLinks = {
    groups: [
      { elements: [{ label: "Home", link: "/", icon: Home }] },
      {
        label: "Settings",
        elements: [{ label: "User", link: "/users", icon: User }],
      },
    ],
  };

  const sessionResponse = await auth.api.getSession({
    headers: await headers(),
  });

  const user = sessionResponse?.user || null;
  if (!user)
    auth.api
      .signOut({
        headers: await headers(),
      })
      .then(redirect("/sign-in"));

  return (
    <html lang="en">
      <body>
        <UserStoreProvider user={user}>
          <BreadcrumStoreProvider>
            <SidebarProvider>
              <AppSidebar links={sidebarLinks} />
              <SidebarInset>
                <AppHeader withSidebarTrigger />
                <main>
                  <AppMain>{children}</AppMain>
                </main>
              </SidebarInset>
            </SidebarProvider>
          </BreadcrumStoreProvider>
        </UserStoreProvider>
      </body>
    </html>
  );
}
